// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtlpServer.Db;

#nullable disable

namespace OtlpServer.Migrations
{
    [DbContext(typeof(TraceContext))]
    partial class TraceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("OtlpServer.Db.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObservedTimeUnixNano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeverityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityText")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("SpanId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimeUnixNano")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("OtlpServer.Db.MetricEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MetricEntries");
                });

            modelBuilder.Entity("OtlpServer.Db.TraceEntry", b =>
                {
                    b.Property<Guid>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SpanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("EndTimeUnixNano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ParentSpanId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("StartTimeUnixNano")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceState")
                        .HasColumnType("TEXT");

                    b.HasKey("TraceId", "SpanId");

                    b.ToTable("TraceEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
